### ISSUE TITLE
User main login and adding AETs

### ISSUE THREAD

**Issue by YanniAlshoufiHTL** [YanniAlshoufiHTL/NiiC#12]
(Please use `pg` (postgresql) library for all SQL related stuff in Node.)
(PLEASE USE QUERY PARAMETERS!!!!!!!!!!! (e.g. `$1::text`))

- [x] Create AET interface on server (the model's name is `NiicAet`, see `/public/src/fe-models/NiicAet`)

- [x] - [ ] Add a `/login` route into the users router (the full route then becomes `/api/users/login`) where you do:
You get:
```
{
     username: "…"
}
```

- [x] Check for user in DB
- [x] If user doesn't exist ⇒ respond with status code `400`
- [x] If user exists get AETs from DB and map them to an array of the `NiicAet` interface
- [x] Respond with `200` and the following body:
```
{
     username: "…",
     aets: […]
}
```

- [x] Add an AET route for adding an AET. The POST route should be `/api/aets/` and the body 
```
{
    username: "…",
    title: "…",
    description: "…",
    (etc., just get all important info for your interface.)
}
```
- [x] The route should then add the AET to the user if the `username` is found, otherwise respond with `400`. If the user is found and the AET was added, answer with http code `201` and with body:

```
{
    id: …
}
```

**Comment by lalaibo** [comment]
finished
