### ISSUE TITLE
Implement First Steps of Token Generation

### ISSUE THREAD

**Issue by YanniAlshoufiHTL** [YanniAlshoufiHTL/NiiC#27]
- [x] Think about a way to store all token information in a string. It should be possible to read everything about the token from the string alone.
- [x] Document the scheme of the token very well and store it in a markdown file a new folder called "/code/docs". Name the file `token-scheme.md`.
- [x] Implement a function that generates the token based on all information needed.
- [x] Implement a route "PUT /api/tokens/" for creating a token and giving it back to the user. When a new token is generated, a module is also generated. Make sure to provide sensible defaults for the block module. Make sure to allow the user to replace an old token. When the user wants to replace an old token, they pass the old token and you should read that token and replace the token from the `blockmodule` with the token provided with the new token.

HINT: There is a table "blockmodule"

**Comment by ClemensGugerbauer** [comment]
Generate tokens and define tokens scheme.
