### ISSUE TITLE
Document as Many Code Duplications, Inconsistent Namings, Parts to Extract, Too long Functions ETC as Possible

### ISSUE THREAD

**Issue by YanniAlshoufiHTL** [YanniAlshoufiHTL/NiiC#36]
- [x] Make a file in the /docs/ folder and name it refactors.md.
- [x] Find code duplications, inconsistent naming conventions, functions that are too long, parts that need extracting, modifications that are necessary, ETC.
- [x] Document those in the refactors.md file.

YOU SHOULD LOOK AT ALL FILES THAT ARE NOT IN THE `out` OR `node_modules` FOLDER (including all Web Components)

**Comment by lalaibo** [comment]
finished with this work
