### ISSUE TITLE
Account Deletion and Log Out

### ISSUE THREAD

**Issue by YanniAlshoufiHTL** [YanniAlshoufiHTL/NiiC#46]
Allow user to delete their account and to log out.

## Data structure

- [x] In the SQL database, add a field named `isloggedin` (boolean value, google how to do that in postgreSQL).
- [x] Add that field to all SQL files.
- [x] Add that field to ALL server and client models.

## Endpoints

Add endpoints for creating (registering), deleting and editing users. Add two further ones for logging in and out. These should be:

For adding, this should return the id if adding was successful.
```
POST /users

{
    "email": string,
    "name": string,
    "password": string
}
```

For editing:
```
PUT /users/:id

{
    "email": string,
    "name": string,
    "password": string
}
```

For deleting:
`DELETE /users/:id`

For logging out:
`PUT /users/logout/:id`

For logging in:
```
POST /users/login

{
    "email": string,
    "name": string,
    "password": string,
}
```

**Comment by lalaibo** [comment]
yay
