### ISSUE TITLE
Login UI Connection with Backend

### ISSUE THREAD

**Issue by YanniAlshoufiHTL** [YanniAlshoufiHTL/NiiC#55]
Connect new login UI to apis, make sure that all endpoints are hooked up correctly. Make sure to adjust the login/signup endpoints on the server to provide you with the JWT that you should then store locally in the `sessionStorage`. Add an HTTP handler called `isAuthenticated`. Please refer to the (wmc-teaching repository)[https://github.com/2324-syp-3ahif/wmc-3-teaching/tree/main/Units/04-Authentication] for details on how to do all of that.

Do NOT add the handler to any endpoints yet.

**Comment by ClemensGugerbauer** [comment]
finished the implementaion of login system
